version:  '3.3'
services:
  nginx:
    image: registry.gitlab.com/bite-industry/crm:master
    container_name: BiteIndustry_CRM
    expose:
      - "80"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=crm.biteindustry.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=crm.biteindustry.com
      - LETSENCRYPT_EMAIL=letsencript@biteindustry.com
    labels:
      "com.centurylinklabs.watchtower.enable": "true"
    networks:
      - app
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy
  app:
